#!/bin/sh

# Set hostname
/bin/hostname -F /etc/hostname

echo "Mounting filesystems"
mount -a
mount

# Disable kernel messages on console
#echo 1 > /proc/sys/kernel/printk

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
    *.sh)
        # Source shell script for speed.
        (
        trap - INT QUIT TSTP
        set start
        . $i
        )
        ;;
    *)
        # No sh extension, so fork subprocess.
        $i start
        ;;
    esac
done

#cat /etc/motd
